
import re
import json
import os

# 1. Ham Veriyi Oku (Mevcut mantık)
raw_data = """
ABDALRAOUF O A BARGHOTH ABDALRAOUF O A BARGHOTH ABDALRAOUF O A  BARGHOUTH
ABDULDAYİM ABDURREZZAK ABDULDAYİM ABDURREZZAK ABDULDAYİM ABDURREZZAK
ABDULHADİ KURTAY ABDULHADİ KURTAY ABDULHADİ KURTAY
EKLENECEK EKLENECEK ABDULKERİM MAĞRİBİ
ABDULLAH ALHANZAL ABDULLAH ALHANZAL ABDULLAH  ALHANZAL 
ABDULMUHSİN HUDYET ABDULMUHSİN HUDYET ABDULMUHSİN  HUDYER
ABDULRAHİM EİD ABDULRAHİM EİD ABDULRAHİM EİD
ABDULRAHMAN KALLAS ABDULRAHMAN KALLAS ABDULRAHMAN KALLAS
ABDULRAHMAN SUKKAR ABDULRAHMAN SUKKAR ABDULRAHMAN SUKKAR
ABDULRAOUF O A BARGHOUTH ABDULRAOUF O A BARGHOUTH SİLİNECEK
ABDURRAHMAN ARAB ABDURRAHMAN ARAB ABDURRAHMAN  ARAB 
ABDURRAHMAN KALLAS ABDURRAHMAN KALLAS SİLİNECEK
ABDURRAHMAN SUKKAR ABDURRAHMAN SUKKAR SİLİNECEK
ABDÜLHADİ KUTAY ABDÜLHADİ KUTAY SİLİNECEK
EKLENECEK EKLENECEK AHMAD KALLAJO
EKLENECEK EKLENECEK AHMAD KOURANI 1
EKLENECEK EKLENECEK AHMAD KOURANI 2
EKLENECEK EKLENECEK AHMAD OLABI
EKLENECEK EKLENECEK AHMED  MUHAMMED SEYFO 
AHMAD KORANİ AHMAD KORANİ SİLİNECEK
AHMED BEŞŞAR EIDO AHMED BEŞŞAR EIDO AHMED BEŞŞAR EIDO
AHMED MUHAMMED SEYİD AHMED MUHAMMED SEYİD SİLİNECEK
EKLENECEK EKLENECEK AHMED EL MUSTAFA
AHMET SOLAKLI AHMET SOLAKLI AHMET SOLAKLI
EKLENECEK EKLENECEK AİŞE KILINÇ
ALAA ALNABHAN ALAA ALNABHAN ALAA ALNABHAN
ALAA EDDİN NALİ ALAA EDDİN NALİ ALAA EDDIN NAJİ
ALAA HABİBİ ALAA HABİBİ SİLİNECEK
ALAA HARIRI ALAA HARIRI ALAA HARIRI
ALAA HARİRİ ALAA HARİRİ SİLİNECEK
ALAA MAHCUB ALAA MAHCUB SİLİNECEK
ALAA MAHCUP ALAA MAHCUP ALAA MAHCUB
EKLENECEK EKLENECEK ALAA OBAİ
ALİ HAMDAN ALİ HAMDAN ALİ HAMDAN
ALİ SALAM ALİ SALAM ALI SALEM
ALİ SALEM ALİ SALEM SİLİNECEK
ALİCAN ALİ ALİCAN ALİ ALİCAN ALİ
ANAS SKAFİ ANAS SKAFİ ANAS SKAFİ
ASLI KAYA ASLI KAYA ASLI  KAYA 
ATAKAN KAYA ATAKAN KAYA ATAKAN KAYA
AYGÜL CEYLAN AYGÜL CEYLAN AYGÜL  CEYLAN 
AYLA SARAÇ AYLA SARAÇ AYLA SARAÇ
AYŞE GİTMEZ AYŞE GİTMEZ AYŞE  GİTMEZ 
AYŞE KARAGÖZ AYŞE KARAGÖZ AYŞE KARAGÖZ
BAHA BALABAN BAHA BALABAN SİLİNECEK
BATIKAN ARSLAN BATIKAN ARSLAN BATIKAN ARSLAN
BİLAL ANTAKİ BİLAL ANTAKİ SİLİNECEK
BİLAL ANTAKLI BİLAL ANTAKLI BİLAL ANTAKLI
BİLGEN YORDAM BİLGEN YORDAM BİLGEN YORDAM
BURAK DOĞAN BURAK DOĞAN BURAK DOĞAN
BÜLENT ŞENGÜL BÜLENT ŞENGÜL BÜLENT ŞENGÜL
CELAL EL MAHFUZ CELAL EL MAHFUZ CELEL EL MAHFUZ 
CELEL EL MAHFUZ CELEL EL MAHFUZ SİLİNECEK
CEMAL ABDULNASIR İSMAİL CEMAL ABDULNASIR İSMAİL CEMAL ABDULNASIR  ESMAİL
CEMAL İSMAİL CEMAL İSMAİL SİLİNECEK
CEMAL KOÇ CEMAL KOÇ CEMAL  KOÇ 
ÇETİN DEVİREN ÇETİN DEVİREN ÇETİN DEVİREN 
EKLENECEK EKLENECEK DIAA SHBIB
DUAA KHAYAT DUAA KHAYAT DUAA KHAYAT
ELİF IŞIK ELİF IŞIK ELİF IŞIK
ELİF TAHTALI ELİF TAHTALI ELİF TAHTALI
ELVAN ÖZDEMİR ELVAN ÖZDEMİR ELVAN ÖZDEMİREL
EMİNE SÜZĞÜN EMİNE SÜZĞÜN SİLİNECEK
EMİNE SÜZÜĞEN EMİNE SÜZÜĞEN EMİNE SİZÜÇEN
EMİRHAN ALREZ EMİRHAN ALREZ EMİRHAN ALREZ
EMİRHAN ZOR EMİRHAN ZOR SİLİNECEK
EMRAH EKBER EMRAH EKBER EMRAH EKBER
EMRE ÇAVDAR EMRE ÇAVDAR EMRE ÇAVDAR
ERDAL ÖZTÜRK ERDAL ÖZTÜRK ERDAL  ÖZTÜRK 
ERKAN DEMİR ERKAN DEMİR ERKAN DEMİR
EKLENECEK EKLENECEK ESMİRA HALİL
ESRA TARIK ESRA TARIK ESRA TARIK
EZEL  ALRIHANI EZEL  ALRIHANI EZEL  ALRIHANI
EZEL ALRHANI EZEL ALRHANI SİLİNECEK
FADİA İBRAHİM BAŞ FADİA İBRAHİM BAŞ SİLİNECEK
FATMA GÜLŞEN FATMA GÜLŞEN SİLİNECEK
FATMA ÖKSÜZ FATMA ÖKSÜZ FATMA ÖKSÜZ
EKLENECEK EKLENECEK FERAS  KANNI 
FERİHA GÜNEŞ FERİHA GÜNEŞ FERİHA GÜLŞEN
FİRDES TAŞAN FİRDES TAŞAN FİRDES TAŞAN 
GAMZE AKCAN GAMZE AKCAN GAMZE AKCAN
GURBET KIYAR GURBET KIYAR GURBET  KIYAR 
GÜLARA ŞEN GÜLARA ŞEN GÜLARA ŞEN
EKLENECEK EKLENECEK GÜLAY GEM
GÜLAY MUTLU GÜLAY MUTLU GÜLAY MUTLU
GÜLER DEMİRDEN GÜLER DEMİRDEN GÜLER DEMİRDEN
GÜLŞEN NİCE GÜLŞEN NİCE GÜLŞEN NİCE
EKLENECEK EKLENECEK HAFİZE ERGÜTEKİN
HAKAN ÖZALP HAKAN ÖZALP HAKAN ÖZALP
HAKTAN ÇAKMAK HAKTAN ÇAKMAK HAKTAN ÇAKMAK
HAMİYET UYMAZ HAMİYET UYMAZ HAMİYET  UYMAZ
EKLENECEK EKLENECEK HAMZA KUTLU
HAMNUT SİDO HAMNUT SİDO SİLİNECEK
HAMZA ASHEM HAMZA ASHEM SİLİNECEK
HAMZA ASHRAM HAMZA ASHRAM HAMZA ASHRAM
EKLENECEK EKLENECEK HANAA ELABDO
HAMZA KUTLU HAMZA KUTLU SİLİNECEK
HANIM ERKUL HANIM ERKUL HANIM ERKUL
EKLENECEK EKLENECEK HASKIZ ERKUL
HASAN YILMAZ HASAN YILMAZ HASAN  YILMAZ 
EKLENECEK EKLENECEK HASSAN HABRA
HASSAN HABRA HASSAN HABRA HASSAN HABRA
HAŞEM   ARİF HAŞEM   ARİF SİLİNECEK
HAŞEM ARİF HAŞEM ARİF HAŞEM  ARİF 
HATİCE DİL HATİCE DİL HATİCE DİL
HAVVA İLBUS HAVVA İLBUS HAVVA İLBUS
HAYSAM KORANİ HAYSAM KORANİ HAYSAM KORANİ
HOSSAM ALDIN ALTAHAN HOSSAM ALDIN ALTAHAN HOSSAM ALDIN  ALTAHAN 
HSAN KAFRNAAR HSAN KAFRNAAR SİLİNECEK
HSAN KAFRNAWI HSAN KAFRNAWI HSAN KAFRNAWI
HURMA DELİYEVA HURMA DELİYEVA SİLİNECEK
SİLİNECEK SİLİNECEK MAHMOUD KOURANI
HURMA DENLİYEVA HURMA DENLİYEVA HURMA DENLİYEVA
HUSAMEDDİN BA HUSAMEDDİN BA SİLİNECEK
HUSSAMALDEEN BAZARBASHI HUSSAMALDEEN BAZARBASHI HUSSAMALDEEN BAZARBASHI
İBRAHİM KAKİRANDİ İBRAHİM KAKİRANDİ SİLİNECEK
İBRAHİM KARANDI İBRAHİM KARANDI IBRAHIM KARKANDI
İBRAHİM KARKANDİ İBRAHİM KARKANDİ SİLİNECEK
EKLENECEK EKLENECEK IMADADDIN HAIK 
İBRAHİM KERİMOĞLU İBRAHİM KERİMOĞLU İBRAHİM KESİMOĞLU
İHSAN KAFKIRAN İHSAN KAFKIRAN SİLİNECEK
İSMAİL ÖMEROĞLU İSMAİL ÖMEROĞLU İSMAİL ÖMEROĞLU
KADRİ NOUSH KADRİ NOUSH KADRİ NOUSH 
KAMURAN MURATGİL KAMURAN MURATGİL KAMURAN MURATGİL 
KERİME AKBAŞ KERİME AKBAŞ SİLİNECEK
KERİME AKHBAŞ KERİME AKHBAŞ KERİME AKHRAS
KÜBRA KUTLU KÜBRA KUTLU KÜBRA  KUTLU
MAHMOUD NASRALLAH MAHMOUD NASRALLAH MAHMOUD  NASRALLAH 
MAHMOUD TAIR MAHMOUD TAIR MAHMOUD TAIR
MAHMUD SİDO MAHMUD SİDO MAHMUD SİDO
EKLENECEK EKLENECEK MAİME ÖZDEMİR
MAJED KHAYATA MAJED KHAYATA MAJED KHAYATA
MAJED KHIYATA MAJED KHIYATA SİLİNECEK
MALİK ŞİMRECİ MALİK ŞİMRECİ MALİK  ŞIMRECİ 
MEHMET ÖZGÜR MEHMET ÖZGÜR MEHMET ÖZGÜR
MERT ASİL MERT ASİL MEHRİBAN ALİ
MHD MOAZ ALSAİD MHD MOAZ ALSAİD MHD MOAZ ALSAID
MHD YAHYA AL KHEN MHD YAHYA AL KHEN SİLİNECEK
MHDINMADEDDİN ZAKRİA MHDINMADEDDİN ZAKRİA MHDIMADEDDIN ZAKRİA
MİHRİBAH ALİ MİHRİBAH ALİ MOHAB KEBBEH WAR
MOHAB KEBBEH WAR MOHAB KEBBEH WAR MOHAMAD  MASSAT 
MOHAMAD AKKA MOHAMAD AKKA MOHAMAD AKKA
MOHAMMAD SHAMMA MOHAMMAD SHAMMA MOHAMAD SHAMMA 
MUHAMED HAMAL MUHAMED HAMAL MUHAMED HAMAL
EKLENECEK EKLENECEK MUHAMMED ELMUHAMMED
MUHAMMED KAMEL ELBANA MUHAMMED KAMEL ELBANA MOHAMED MOHAMED MOHAMED KAMEL  ELBANA 
MUHAMMED KASSAB MUHAMMED KASSAB MUHAMMED KASSAB
MUHAMMED ZÜHEYR MAĞHİNİ MUHAMMED ZÜHEYR MAĞHİNİ MUHAMMED ZÜHEYR MAĞRİBİ
MUHANNED CEBBULİ MUHANNED CEBBULİ MUHANNED CEBBULİ
MUSTAFA AVŞAR MUSTAFA AVŞAR MUSTAFA AVŞAR
MUSTAFA GAŞİM MUSTAFA GAŞİM MUSTAFA  GAŞİM 
MÜNEVER ÇETİN MÜNEVER ÇETİN MÜNEVVER  ÇETİN 
NAURAS EL MASRE NAURAS EL MASRE SİLİNECEK
EKLENECEK EKLENECEK NERMİN DEMİR
NESRİN ADA NESRİN ADA NESRİN ADA
NEVRAZ ALNASRİ NEVRAZ ALNASRİ NEVRAZ ALNASRİ
NİDAL ALALI NİDAL ALALI NİDAL  ALALI
NURETTİN SOLAKLI NURETTİN SOLAKLI NURETTİN SOLAKLI
NURİYE ATASOY NURİYE ATASOY NURİYE ATASOY
OMAR SALEM OMAR SALEM OMAR SALEM
ORHAN KALIN ORHAN KALIN ORHAN KALIN
EKLENECEK EKLENECEK OSAMA FEDDO
OYA ERDOĞAN OYA ERDOĞAN OYA ERDOĞAN
ÖZLEM YORDAM ÖZLEM YORDAM ÖZLEM  YORDAM 
RABİA İBRAHİMBAŞ RABİA İBRAHİMBAŞ RABİA İBRAHİMBAŞ
EKLENECEK EKLENECEK RAZAN ALBADER
RECEP SOLAKLI RECEP SOLAKLI RECEP SOLAKLI
RIDVAN KURTAY RIDVAN KURTAY RIDVAN KURTAY
RÜMEYSA YAŞAR RÜMEYSA YAŞAR RÜMEYSA YAŞAR
SAAD HABRA SAAD HABRA SAAD HABRA
SAİD ABDULBAKİ SAİD ABDULBAKİ SAİD ABDULBAKİ
SAİME TOPRAK SAİME TOPRAK SAİME TOPRAK
SAMİA HAG ALİİ SAMİA HAG ALİİ SAMİA HAG ALİİ
SEFER CAN ER SEFER CAN ER SEFER CAN ER
SEHER  ÖZATİLA SEHER  ÖZATİLA SEHER  ÖZATİLA
EKLENECEK EKLENECEK SELİM ARSLANTÜRK
SEMRA YILDIRIM SEMRA YILDIRIM SEMRA YILDIRIM
EKLENECEK EKLENECEK SENA KENNO 
SERKAN BEY SERKAN BEY SERKAN BEY
EKLENECEK EKLENECEK SERKAN ÖZYÜREK
EKLENECEK EKLENECEK SEVGİ İSLAM
EKLENECEK EKLENECEK SONGÜL ERDAL
SUDE ÖZBAYRAK SUDE ÖZBAYRAK SUDE ÖZBAYRAK
SULEYMAN SİDO SULEYMAN SİDO SULEYMAN  SİDO 
SUNA YILDIZ SUNA YILDIZ SUNA YILDIZ
ŞEHRİYE YAŞAR ŞEHRİYE YAŞAR ŞEHRİYE YAŞAR
ŞERAFEDDİN SÖZEN ŞERAFEDDİN SÖZEN ŞERAFEDDİN  SÖZEN 
ŞERİFE DENİZ ŞERİFE DENİZ ŞERİFE DENİZ
TALİP BELLURA TALİP BELLURA TALİP BELLURA
TAYFUN KAYNAR TAYFUN KAYNAR TAYFUN KAYNAR
TELAL ŞAKİFA TELAL ŞAKİFA TELAL ŞAKİFA
TURGAY BARUTÇU TURGAY BARUTÇU TURGAY BARUTÇU
UĞUR ÜNLÜSOY UĞUR ÜNLÜSOY UĞUR  ÜNLÜSOY 
UMUT ALACA UMUT ALACA UMUT  ALACA 
UMUT CAN KURTAY UMUT CAN KURTAY UMUT CAN  KURTAY 
ÜMMÜHAN ORUÇ ÜMMÜHAN ORUÇ ÜMMÜHAN  ORUÇ
EKLENECEK EKLENECEK ÜNZİLE ÖZEL
VAGIF MEHDİ VAGIF MEHDİ VAGIF MEHDİ
VECHETTİN GÜNEŞ VECHETTİN GÜNEŞ VECHETTİN GÜNEŞ
VELED ALAMRA VELED ALAMRA SİLİNECEK
VELED İBRAHİM VELED İBRAHİM SİLİNECEK
VELİD ALAMRA VELİD ALAMRA VELİD ALAMRA
VELİD İBRAHİM VELİD İBRAHİM VELİD İBRAHİM
YAHYA ALKAN YAHYA ALKAN YAHYA ALKAN
YAMEN KENAAN YAMEN KENAAN YAMEN  KENAAN 
YASEMİN SAKARYA YASEMİN SAKARYA YASEMİN  SAKARYA 
YASER HAVCEH YASER HAVCEH YASER HAVCEH
YELİZ ÇAKIR YELİZ ÇAKIR YELİZ ÇAKIR
YSEMİN SAKARYA YSEMİN SAKARYA SİLİNECEK
ZEYNEP ALBAYRAK ZEYNEP ALBAYRAK ZEYNEP ALBAYRAK
EKLENECEK EKLENECEK ZİLAL EL REMMO 
ZUBALA  MEHDİ ZUBALA  MEHDİ ZUBALA  MEHDİ 
ZÜLFİYE ÇETİN ZÜLFİYE ÇETİN ZÜLFÜYE ÇETİN
"""

added = []
deleted = []
renamed = {} # Map old_name -> new_name
final_names = []

lines = [l.strip() for l in raw_data.strip().split('\n') if l.strip()]

for line in lines:
    line = re.sub(r'\s+', ' ', line)
    
    # CASE 1: EKLENECEK
    if line.startswith("EKLENECEK EKLENECEK"):
        name = line.replace("EKLENECEK EKLENECEK", "").strip()
        added.append(name)
        final_names.append(name)
        continue
    
    # CASE 2: SİLİNECEK suffix
    if line.endswith(" SİLİNECEK"):
        content = line.replace(" SİLİNECEK", "")
        # Parsing logic from previous attempt
        words = content.split(' ')
        mid = len(words) // 2
        
        # Assume repeated part
        part1 = " ".join(words[:mid])
        deleted.append(part1)
        # NOT adding to final_names
        continue

    # CASE Special: SİLİNECEK prefix
    if line.startswith("SİLİNECEK SİLİNECEK"):
        name = line.replace("SİLİNECEK SİLİNECEK", "").strip()
        deleted.append(name)
        continue
        
    # CASE 3 & 4: UPDATE OR UNCHANGED
    words = line.split(' ')
    found = False
    for n in range(1, len(words) // 2 + 1):
        A = words[0:n]
        B = words[n:2*n]
        
        if A == B:
            old_name = " ".join(A)
            new_name = " ".join(words[2*n:])
            
            if not new_name: 
                continue

            # Clean new_name logic? Maybe trim spaces?
            new_name = new_name.strip()
            
            # Add to final list
            final_names.append(new_name)
            
            # Check if renamed
            if old_name != new_name:
                renamed[old_name] = new_name
            
            found = True
            break
            
    if not found:
        # Fallback: assume it's kept as is, but maybe parse error?
        # For safety, let's treat the whole line as the name if it's short, or skip?
        # In this dataset, everything fits patterns. Assuming skip is bad.
        # Let's inspect "MUHAMMED KAMEL ELBANA..." case again implicitly handled by existing logic or skipped.
        # Actually logic above might miss complex ones.
        # "MUHAMMED KAMEL ELBANA MUHAMMED KAMEL ELBANA MOHAMED MOHAMED MOHAMED KAMEL ELBANA"
        # A=3 words, B=3 words. Total 11 words. 3+3=6. 11-6=5 (New Name). MATCHES.
        # It should work.
        pass

# Sort final list for clean look
final_names.sort()

# --- OUTPUT 1: Human Readable Final List ---
with open('target_personnel_list.txt', 'w', encoding='utf-8') as f:
    f.write("--- NİHAİ PERSONEL LİSTESİ ---\n")
    f.write(f"Toplam Kişi: {len(final_names)}\n")
    f.write("-" * 30 + "\n")
    for name in final_names:
        f.write(f"{name}\n")
        
# --- OUTPUT 2: Machine Readable Payload ---
payload = {
    "target_list": final_names,
    "renames": renamed, # {old: new}
    "explicit_adds": added, # List of names definitely new
    "explicit_deletes": deleted # List of names definitely deleted (for verification only, target_list is authority)
}

with open('sync_payload.json', 'w', encoding='utf-8') as f:
    json.dump(payload, f, ensure_ascii=False, indent=2)

print(f"Generated 'target_personnel_list.txt' with {len(final_names)} names.")
print(f"Generated 'sync_payload.json' for the apply script.")
